quarkus-run:
  replicaCount: 5

  rollout:
    steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}  

  podEnvironmentVariables:
    - name: QUARKUS_PROFILE
      value: prod       